config/routes.rb
Rails.application.routes.draw do

  resources :cars do
    resources :histories, shallow: true, only: [:new, :show, :destroy]

    resources :annual_inspection_histories, shallow: true,    except: [:index]
    resources :compulsory_insurance_histories, shallow: true, except: [:index]
    resources :production_histories, shallow: true,           except: [:index, :new, :create, :destroy]
    resources :purchase_histories, shallow: true,             except: [:index, :new, :create, :destroy]
    resources :full_insurance_histories, shallow: true,       except: [:index]
    resources :maintenance_histories, shallow: true,          except: [:index]
    resources :repairment_histories, shallow: true,           except: [:index]
    resources :tax_histories, shallow: true,                  except: [:index]
    resources :tuning_histories, shallow: true,               except: [:index]
    resources :vignette_histories, shallow: true,             except: [:index]
    resources :tyre_histories, shallow: true,                 except: [:index]

    namespace :statistics do
      get '/expences/all_time',      to: 'expenses#all_time'
      get '/expences/last_year',     to: 'expenses#last_year'
      get '/expences/cost_by_month', to: 'expenses#cost_by_month'
      get '/expences/cost_by_type',  to: 'expenses#cost_by_type'

      root to: 'expenses#all_time'
    end
  end

  resources :notifications, only: [:index] do
    member do
      patch 'read'
    end
  end

  namespace :facebook do
    post '/notifications/:id', to: 'notifications#show'
  end

  # Omniauth
  get    '/auth/facebook/callback',   to: 'facebook_sessions#create'
  get    '/auth/failure',             to: 'static_pages#landingpage'

  get    '/signin',                   to: 'sessions#new'
  get    '/signup',                   to: 'users#new'
  post   '/signup',                   to: 'users#create'
  post   '/signin',                   to: 'sessions#create'
  delete '/signout',                  to: 'sessions#destroy'
  get    '/settings',                 to: 'settings#edit'
  patch  '/settings',                 to: 'settings#update'

  post   '/demo',                     to: 'guest_users#create'

  resource :user, only: %i(show edit update destroy) do
    get    '/password/edit',    to: 'passwords#edit'
    patch  '/password',         to: 'passwords#update'
  end

  resource :password_reset, only: [:new, :create, :edit, :update]

  get '/contacts',     to: 'static_pages#contacts'
  get '/terms_of_use', to: 'static_pages#terms_of_use'
  get '/privacy_policy', to: 'static_pages#privacy_policy'

  resources :locations, only: [:index, :show]

  namespace :admin do
    resources :users, only: [:index] do
      resources :cars, only: [:index]
    end

    resources :cars, only: [:index, :edit, :update] do
      resources :histories, only: [:index]
    end

    resources :locations

    namespace :statistics do
      get '/users/overview', to: 'users#overview'
      get '/users/signups', to: 'users#signups'
      get '/users/signins', to: 'users#signins'

      get '/car/creations', to: 'cars#creations'

      get '/history/creations', to: 'histories#creations'

      root to: 'base#overview'
    end

    root to: "users#index"
  end

  root to: "static_pages#landingpage"
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :vehicle_inspections, dependent: :destroy

  validates :name,
            :address,
            :settlement,
            :settlement_type,
            :latitude,
            :longitude, presence: true

  enum settlement_type: [:unknown, :city, :village]
  enum status: [:unprocessed, :approved_for_map, :not_approved_for_map]

  scope :with_defined_geolocation, -> { where.not('latitude = ? OR longitude = ?', Bulgaria::LATITUDE, Bulgaria::LONGITUDE) }
  scope :with_default_geolocation, -> { where('latitude = ? AND longitude = ?', Bulgaria::LATITUDE, Bulgaria::LONGITUDE) }
end

app/controllers/admin/locations_controller.rb
module Admin
  class LocationsController < BaseController
    before_action :load_map_javascript, only: [:new, :edit]

    def index
      @tab = Tab.new params[:tab]
      @locations_approved_for_map = Location.approved_for_map.order(settlement: :asc)
      @locations_not_approved_for_map = Location.not_approved_for_map.order(settlement: :asc)
      @unprocessed_locations = Location.unprocessed.order(settlement: :asc)

      @locations = if @tab.approved_for_map?
                     @locations_approved_for_map
                   elsif @tab.not_approved_for_map?
                     @locations_not_approved_for_map
                   else
                     @unprocessed_locations
                   end
    end

    def show
    end

    def new
      @location = Location.new(latitude: Bulgaria::LATITUDE, longitude: Bulgaria::LONGITUDE)
    end

    def create
      @location = Location.new(location_params)

      if @location.save
        redirect_to admin_locations_path
      else
        render :new
      end
    end

    def edit
      @location = Location.find(params[:id])
    end

    def update
      @location = Location.find(params[:id])

      if @location.update_attributes(location_params)
        redirect_to admin_locations_path
      else
        render :edit
      end
    end

    def destroy
      location = Location.find(params[:id])
      location.destroy
      redirect_to admin_locations_path
    end

    private

    def location_params
      params.
        require(:location).
        permit(:name, :settlement, :settlement_type, :status, :address, :longitude, :latitude)
    end
  end

  class Tab
    def initialize(name)
      @approved_for_map = false
      @not_approved_for_map = false
      @unprocessed = false

      if name == 'approved_for_map'
        @approved_for_map = true
      elsif name == 'not_approved_for_map'
        @not_approved_for_map = true
      else
        @unprocessed = true
      end
    end

    def approved_for_map?
      @approved_for_map
    end

    def not_approved_for_map?
      @not_approved_for_map
    end

    def unprocessed?
      @unprocessed
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :load_map_clustering_javascript, only: [:index]
  before_action :load_map_javascript, only: [:index]

  def index
    @locations = if params[:approved_for_map]
                   Location.approved_for_map
                 else
                   Location.all.order(settlement: :asc)
                 end

    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
    @location = Location.find params[:id]

    respond_to do |format|
      format.json
    end
  end
end

app/views/admin/locations/_form.slim
= bootstrap_form_for [:admin, location] do |f|
  .form-group
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.select :settlement_type, Location.settlement_types.keys.to_a, {}, class: 'form-control'

  .form-group
    = f.select :status, Location.statuses.keys.to_a, {}, class: 'form-control'

  .form-group
    = f.text_field :settlement, class: 'form-control'

  .form-group
    = f.text_field :address, class: 'form-control'

  .form-group
    .map.map_fixed-height
      .map__backsight
      .map__canvas {
                      data-lat="#{f.object.latitude}"
                      data-lng="#{f.object.longitude}"
                      data-zoom="18"
                    }

    = text_field_tag :pac_input, nil, id: 'pac-input', class: 'map__input_search controls', placeholder: 'Търсене ...', style: 'margin: 15px 2%; width: 96%; height: 36px; line-height: 36px; font-size: 16px; padding: 5px;'

    = f.text_field :latitude, class: 'form-control', class: 'map__input map__input_lat', style: 'display: block;'
    = f.text_field :longitude, class: 'form-control', class: 'map__input map__input_lng', style: 'display: block;'

  = f.submit class: 'btn btn-primary'
  | &nbsp;
  = link_to 'Отказ', admin_locations_path, class: 'btn btn-default'

app/views/admin/locations/edit.html.slim
h1 Редакция на локация

= render partial: 'form', locals: { location: @location }

app/views/admin/locations/index.html.slim
h1 Справочник

br

.row
  .col-xs-12
    ul.nav.nav-tabs
      li class="#{'active' if @tab.approved_for_map? }"
        = link_to admin_locations_path(tab: 'approved_for_map') do
          'Одобрени
          span.badge = @locations_approved_for_map.count

      li class="#{'active' if @tab.not_approved_for_map? }"
        = link_to admin_locations_path(tab: 'not_approved_for_map') do
          'Неодобрени
          span.badge = @locations_not_approved_for_map.count

      li class="#{'active' if @tab.unprocessed? }"
        = link_to admin_locations_path(tab: 'unprocessed') do
          'Непрегледани
          span.badge = @unprocessed_locations.count


br

= link_to 'Нова локация', new_admin_location_path, class: 'btn btn-primary'

br

.table-responsive
  table.table.table-striped
    thead
      tr
        th Град
        th Име
        th Адрес
        th &nbsp;
        th &nbsp;

    tbody
      - @locations.each do |location|
        tr
          td = location.settlement
          td = location.name
          td = location.address
          td
            = link_to 'Редакция', edit_admin_location_path(location), class: 'btn btn-default btn-xs'
          td
            = link_to 'Изтриване', admin_location_path(location), method: :delete, class: 'btn btn-danger btn-xs', data: {confirm: 'Сигурен ли си?'}

app/views/admin/locations/new.html.slim
h1 Нова локация

= render partial: 'form', locals: { location: @location }