config/routes.rb
Rails.application.routes.draw do

  resources :cars do
    resources :histories, shallow: true, only: [:new, :show, :destroy]

    resources :annual_inspection_histories, shallow: true,    except: [:index]
    resources :compulsory_insurance_histories, shallow: true, except: [:index]
    resources :production_histories, shallow: true,           except: [:index, :new, :create, :destroy]
    resources :purchase_histories, shallow: true,             except: [:index, :new, :create, :destroy]
    resources :full_insurance_histories, shallow: true,       except: [:index]
    resources :maintenance_histories, shallow: true,          except: [:index]
    resources :repairment_histories, shallow: true,           except: [:index]
    resources :tax_histories, shallow: true,                  except: [:index]
    resources :tuning_histories, shallow: true,               except: [:index]
    resources :vignette_histories, shallow: true,             except: [:index]
    resources :tyre_histories, shallow: true,                 except: [:index]

    namespace :statistics do
      get '/expences/all_time',      to: 'expenses#all_time'
      get '/expences/last_year',     to: 'expenses#last_year'
      get '/expences/cost_by_month', to: 'expenses#cost_by_month'
      get '/expences/cost_by_type',  to: 'expenses#cost_by_type'

      root to: 'expenses#all_time'
    end
  end

  resources :notifications, only: [:index] do
    member do
      patch 'read'
    end
  end

  namespace :facebook do
    post '/notifications/:id', to: 'notifications#show'
  end

  # Omniauth
  get    '/auth/facebook/callback',   to: 'facebook_sessions#create'
  get    '/auth/failure',             to: 'static_pages#landingpage'

  get    '/signin',                   to: 'sessions#new'
  get    '/signup',                   to: 'users#new'
  post   '/signup',                   to: 'users#create'
  post   '/signin',                   to: 'sessions#create'
  delete '/signout',                  to: 'sessions#destroy'
  get    '/settings',                 to: 'settings#edit'
  patch  '/settings',                 to: 'settings#update'

  post   '/demo',                     to: 'guest_users#create'

  resource :user, only: %i(show edit update destroy) do
    get    '/password/edit',    to: 'passwords#edit'
    patch  '/password',         to: 'passwords#update'
  end

  resource :password_reset, only: [:new, :create, :edit, :update]

  get '/contacts',     to: 'static_pages#contacts'
  get '/terms_of_use', to: 'static_pages#terms_of_use'
  get '/privacy_policy', to: 'static_pages#privacy_policy'

  resources :locations, only: [:index, :show]

  namespace :admin do
    resources :users, only: [:index] do
      resources :cars, only: [:index]
    end

    resources :cars, only: [:index, :edit, :update] do
      resources :histories, only: [:index]
    end

    resources :locations

    namespace :statistics do
      get '/users/overview', to: 'users#overview'
      get '/users/signups', to: 'users#signups'
      get '/users/signins', to: 'users#signins'

      get '/car/creations', to: 'cars#creations'

      get '/history/creations', to: 'histories#creations'

      root to: 'base#overview'
    end

    root to: "users#index"
  end

  root to: "static_pages#landingpage"
end

app/models/vignette_history.rb
class VignetteHistory < History
end

app/controllers/vignette_histories_controller.rb
class VignetteHistoriesController < HistoriesController
  def show
  end

  def new
    @history = VignetteHistory.new(mileage: @car.current_mileage)
  end

  def create
    @history = VignetteHistory.new(history_params.merge(car_id: @car.id))

    if @history.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  private

  def history_params
    if params[:vignette_history].present?
      params[:vignette_history].permit(:happened_at, :mileage, :valid_until, :cost, :details).to_h
    else
      {}
    end
  end
end

app/views/vignette_histories/_side_panel.slim
.panel.panel-default
  .panel-heading
    strong Помощ

  .panel-body
    p Въведи информация за закупена винетка.

app/views/vignette_histories/edit.html.slim
= render partial: 'cars/header', locals: { cars: @cars, active_tab: @car.id }

br

.row
  .col-sm-12
    = link_to back_or_default, class: 'btn btn-default' do
      = fa_icon 'chevron-left'
      | &nbsp; &nbsp;
      | Назад

br

.row
  .col-sm-9
    .row
      .col-xs-12
        .panel.panel-default
          .panel-heading
            strong Редакия на данни за винетка
          .panel-body
            = bootstrap_form_for @history do |f|
              = f.date_select :happened_at, { order: [:day, :month, :year], start_year: 1900, end_year: Date.today.year }, { class: 'form-control date-select' }
              = f.text_field :cost, class: 'form-control'
              = f.date_select :valid_until, { order: [:day, :month, :year], start_year: Date.today.year - 10 }, { class: 'form-control date-select' }
              = f.number_field :mileage, class: 'form-control'
              = f.text_area :details, class: 'form-control wysihtml5', rows: 5

              .form-group
                = f.submit 'Редактирай', class: 'btn btn-primary'
                | &nbsp;
                = link_to 'Отказ', back_or_default, class: 'btn btn-default'

  .col-sm-3

app/views/vignette_histories/new.html.slim
= render partial: 'cars/header', locals: { cars: @cars, active_tab: @car.id }

br

.row
  .col-sm-12
    = link_to new_car_history_path, class: 'btn btn-default' do
      = fa_icon 'chevron-left'
      | &nbsp; &nbsp;
      | Назад

br

.row
  .col-sm-9
    .row
      .col-xs-12
        .panel.panel-default
          .panel-heading
            strong Добавяне на винетка
          .panel-body
            = bootstrap_form_for [@car, @history] do |f|
              = f.date_select :happened_at, { order: [:day, :month, :year], start_year: 1900, end_year: Date.today.year }, { class: 'form-control date-select' }
              = f.text_field :cost, class: 'form-control', placeholder: 'Стойност на винетката (лв.)'
              = f.date_select :valid_until, { order: [:day, :month, :year], start_year: Date.today.year - 10 }, { class: 'form-control date-select' }
              = f.number_field :mileage, class: 'form-control', placeholder: 'Пробег в момента на покупката (км.)'
              = f.text_area :details, class: 'form-control wysihtml5', rows: 5, placeholder: 'Пример: Едномесечна винетка'

              .form-group
                = f.submit 'Добави винетка', class: 'btn btn-primary'
                | &nbsp;
                = link_to 'Отказ', back_or_default, class: 'btn btn-default'

  .col-sm-3
    = render partial: 'side_panel'

app/views/vignette_histories/show.html.slim
= render partial: 'cars/header', locals: { cars: @cars, active_tab: @car.id }

br

.row
  .col-sm-12
    = link_to back_or_default, class: 'btn btn-default' do
      = fa_icon 'chevron-left'
      | &nbsp; &nbsp;
      | Назад

br

.row
  .col-sm-9
    .panel.panel-default
      .panel-heading
        strong Винетка

      table.table.table-bordered
        tr
          th Дата на събитие
          td = @history.happened_at.strftime("%d.%m.%Y")
        tr
          th Дата на въвеждане
          td = @history.created_at.strftime("%d.%m.%Y")
        tr
          th Валиден до
          td = @history.valid_until.strftime("%d.%m.%Y")
        tr
          th Стойност
          td = number_to_currency(@history.cost, locale: I18n.locale)
        tr
          th Пробег
          td
            - if @history.mileage.present?
              = number_with_delimiter(@history.mileage, delimiter: ',') + " км."
        tr
          th Детайли
          td
            - if @history.details.present?
              = @history.details.html_safe

  .col-sm-3
    .panel.panel-default
      .panel-heading
        strong Действия

      .panel-body
        = link_to 'Редактирай', edit_vignette_history_path(@history), class: 'btn btn-block btn-primary'
        = link_to 'Изтрий', history_path(@history), class: 'btn btn-block btn-danger', data: {:confirm => "Сигурни ли сте?"}, :method => :delete