config/routes.rb
Rails.application.routes.draw do

  resources :cars do
    resources :histories, shallow: true, only: [:new, :show, :destroy]

    resources :annual_inspection_histories, shallow: true,    except: [:index]
    resources :compulsory_insurance_histories, shallow: true, except: [:index]
    resources :production_histories, shallow: true,           except: [:index, :new, :create, :destroy]
    resources :purchase_histories, shallow: true,             except: [:index, :new, :create, :destroy]
    resources :full_insurance_histories, shallow: true,       except: [:index]
    resources :maintenance_histories, shallow: true,          except: [:index]
    resources :repairment_histories, shallow: true,           except: [:index]
    resources :tax_histories, shallow: true,                  except: [:index]
    resources :tuning_histories, shallow: true,               except: [:index]
    resources :vignette_histories, shallow: true,             except: [:index]
    resources :tyre_histories, shallow: true,                 except: [:index]

    namespace :statistics do
      get '/expences/all_time',      to: 'expenses#all_time'
      get '/expences/last_year',     to: 'expenses#last_year'
      get '/expences/cost_by_month', to: 'expenses#cost_by_month'
      get '/expences/cost_by_type',  to: 'expenses#cost_by_type'

      root to: 'expenses#all_time'
    end
  end

  resources :notifications, only: [:index] do
    member do
      patch 'read'
    end
  end

  namespace :facebook do
    post '/notifications/:id', to: 'notifications#show'
  end

  # Omniauth
  get    '/auth/facebook/callback',   to: 'facebook_sessions#create'
  get    '/auth/failure',             to: 'static_pages#landingpage'

  get    '/signin',                   to: 'sessions#new'
  get    '/signup',                   to: 'users#new'
  post   '/signup',                   to: 'users#create'
  post   '/signin',                   to: 'sessions#create'
  delete '/signout',                  to: 'sessions#destroy'
  get    '/settings',                 to: 'settings#edit'
  patch  '/settings',                 to: 'settings#update'

  post   '/demo',                     to: 'guest_users#create'

  resource :user, only: %i(show edit update destroy) do
    get    '/password/edit',    to: 'passwords#edit'
    patch  '/password',         to: 'passwords#update'
  end

  resource :password_reset, only: [:new, :create, :edit, :update]

  get '/contacts',     to: 'static_pages#contacts'
  get '/terms_of_use', to: 'static_pages#terms_of_use'
  get '/privacy_policy', to: 'static_pages#privacy_policy'

  resources :locations, only: [:index, :show]

  namespace :admin do
    resources :users, only: [:index] do
      resources :cars, only: [:index]
    end

    resources :cars, only: [:index, :edit, :update] do
      resources :histories, only: [:index]
    end

    resources :locations

    namespace :statistics do
      get '/users/overview', to: 'users#overview'
      get '/users/signups', to: 'users#signups'
      get '/users/signins', to: 'users#signins'

      get '/car/creations', to: 'cars#creations'

      get '/history/creations', to: 'histories#creations'

      root to: 'base#overview'
    end

    root to: "users#index"
  end

  root to: "static_pages#landingpage"
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :car
  has_many :notifications, as: :notifiable, dependent: :destroy

  validates :mileage, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_blank: true

  validates :happened_at, presence: true
  validates :cost, numericality: { allow_blank: true, greater_than_or_equal_to: 0 }
  validate :valid_until_is_after_happened_at

  def notify_about_expiration?
    expiration_notification_class.present?
  end

  def expiration_notification_class
    nil
  end

  def notify_expiration
    # Do nothing
  end

  private

  def valid_until_is_after_happened_at
    if valid_until.present? && valid_until < happened_at
      errors.add(:valid_until, I18n.t('activerecord.errors.models.history.attributes.valid_until.in_the_past'))
    end
  end
end

app/controllers/admin/histories_controller.rb
module Admin
  class HistoriesController < BaseController
    def index
      @car = Car.find(params[:car_id])
      @histories = @car.histories.order(created_at: :desc)
    end
  end
end

app/controllers/admin/statistics/histories_controller.rb
module Admin
  module Statistics
    class HistoriesController < BaseController
      def creations
        @history_creations = ::Statistics::Chartjs::HistoryCreations.new(Date.today - 1.month, Date.today)
      end
    end
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :requires_login
  before_action :set_car_instance_variables,    only: [:new, :create]
  before_action :set_history_instance_variable, only: [:show, :edit, :update, :destroy]

  def show
    case @history
    when AnnualInspectionHistory
      redirect_to annual_inspection_history_path(@history, referrer_param => back_or_default)
    when CompulsoryInsuranceHistory
      redirect_to compulsory_insurance_history_path(@history, referrer_param => back_or_default)
    when PurchaseHistory
      redirect_to purchase_history_path(@history, referrer_param => back_or_default)
    when ProductionHistory
      redirect_to production_history_path(@history, referrer_param => back_or_default)
    when FullInsuranceHistory
      redirect_to full_insurance_history_path(@history, referrer_param => back_or_default)
    when MaintenanceHistory
      redirect_to maintenance_history_path(@history, referrer_param => back_or_default)
    when RepairmentHistory
      redirect_to repairment_history_path(@history, referrer_param => back_or_default)
    when TaxHistory
      redirect_to tax_history_path(@history, referrer_param => back_or_default)
    when TuningHistory
      redirect_to tuning_history_path(@history, referrer_param => back_or_default)
    when TyreHistory
      redirect_to tyre_history_path(@history, referrer_param => back_or_default)
    when VignetteHistory
      redirect_to vignette_history_path(@history, referrer_param => back_or_default)
    else
      redirect_to back_or_default
    end
  end

  def edit
  end

  def update
    if @history.update_attributes(history_params)
      redirect_to back_or_default
    else
      render :edit
    end
  end

  def destroy
    @history.destroy
    redirect_to back_or_default
  end

  protected

  def default_path
    if referrer_path
      referrer_path
    elsif @history && @history.car
      car_path(@history.car)
    else
      cars_path
    end
  end

  private

  def history_params
    {}
  end

  def set_history_instance_variable
    @history = current_user.histories.find(params[:id])
    @cars = current_user.cars
    @car  = @history.car
  end

  def set_car_instance_variables
    @cars = current_user.cars
    @car  = @cars.find(params[:car_id])
  end
end

app/views/histories/_side_panel.slim
.panel.panel-default
  .panel-heading
    strong Помощ

  .panel-body
    p Избери категория на история.

app/views/histories/_table.slim
.table-responsive
  table.table.table-hover.histories-table
    thead
      tr
        th &nbsp;
        th Дата на събитие
        th Пробег
        th Детайли
        th Стойност

    tbody
      - if histories.any?
        - histories.each do |history|
          tr
            td = link_to fa_icon('search'), history_path(history, referrer_param => current_path), class: 'btn btn-default btn-xs'
            td = history.happened_at.strftime("%d.%m.%Y")
            td
              - if history.mileage.present?
                = number_with_delimiter(history.mileage, delimiter: ',') + " км."
            td.histories-table__col_details
              h5.title = t("activerecord.attributes.history.types.#{history.type}")
              - if history.details.present?
                .description = history.details.html_safe
            td = number_to_currency(history.cost, locale: I18n.locale)

      - else
        tr.text-center
          td colspan="5" Няма записана история за тази кола.

app/views/histories/new.html.slim
= render partial: 'cars/header', locals: { cars: @cars, active_tab: @car.id }

br

.row
  .col-sm-12
    = link_to back_or_default, class: 'btn btn-default' do
      = fa_icon 'chevron-left'
      | &nbsp; &nbsp;
      | Назад

br

.row
  .col-sm-9
    .row
      .col-xs-12
        .panel.panel-default
          .panel-heading
            strong Избери категория
          .panel-body
            ul.history-type-select
              li
                = link_to new_car_repairment_history_path, class: 'history-type-option' do
                  = image_tag 'car/car-secure.png'
                  p Ремонт

              li
                = link_to new_car_maintenance_history_path, class: 'history-type-option' do
                  = image_tag 'car/car-with-oil-sign.png'
                  p Обслужване

              li
                = link_to new_car_annual_inspection_history_path, class: 'history-type-option' do
                  = image_tag 'car/checked-car.png'
                  p Годишен технически преглед (ГТП)

              li
                = link_to new_car_compulsory_insurance_history_path, class: 'history-type-option' do
                  = image_tag 'car/car-accident.png'
                  p Гражданска отговорност (ГО)

              li
                = link_to new_car_full_insurance_history_path, class: 'history-type-option' do
                  = image_tag 'car/umbrella-car.png'
                  p Каско

              li
                = link_to new_car_tyre_history_path, class: 'history-type-option' do
                  = image_tag 'car/car-with-spare-tire.png'
                  p Гуми

              li
                = link_to new_car_vignette_history_path, class: 'history-type-option' do
                  = image_tag 'car/front-car.png'
                  p Винетка

              li
                = link_to new_car_tax_history_path, class: 'history-type-option' do
                  = image_tag 'car/front-car.png'
                  p Данък

              li
                = link_to new_car_tuning_history_path, class: 'history-type-option' do
                  = image_tag 'car/change-gear.png'
                  p Подобрение

  .col-sm-3
    = render partial: 'side_panel'